# Docker Compose for Development
version: "3.9"

services:
  # MongoDB Database
  mongodb:
    image: mongo:7-jammy
    container_name: backend-template-mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: backend_template_dev
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - backend-network

  # Backend Application
  backend:
    container_name: backend-template-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/backend_template_dev?authSource=admin
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    depends_on:
      - mongodb
    networks:
      - backend-network
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: package.json

volumes:
  mongodb_data:
    driver: local

networks:
  backend-network:
    driver: bridge
